/*! Copyright © 2015, 2018, Oracle and/or its affiliates. All rights reserved. */
/*! mmpackage v1.16 */
/*! jQuery | Copyright JS Foundation and other contributors, https://js.foundation */
/*v1.16.0.8*/
'use strict';var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(A,r,C){A instanceof String&&(A=String(A));for(var H=A.length,E=0;E<H;E++){var U=A[E];if(r.call(C,U,E,A))return{i:E,v:U}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(A,r,C){A!=Array.prototype&&A!=Object.prototype&&(A[r]=C.value)};
$jscomp.getGlobal=function(A){return"undefined"!=typeof window&&window===A?A:"undefined"!=typeof global&&null!=global?global:A};$jscomp.global=$jscomp.getGlobal(this);$jscomp.polyfill=function(A,r,C,H){if(r){C=$jscomp.global;A=A.split(".");for(H=0;H<A.length-1;H++){var E=A[H];E in C||(C[E]={});C=C[E]}A=A[A.length-1];H=C[A];r=r(H);r!=H&&null!=r&&$jscomp.defineProperty(C,A,{configurable:!0,writable:!0,value:r})}};
$jscomp.polyfill("Array.prototype.find",function(A){return A?A:function(r,A){return $jscomp.findInternal(this,r,A).v}},"es6-impl","es3");
(function(){function A(r,H,E){A=void 0;(new Function("scriptName","applier",r))(H,E)}var r=window.console||{log:function(){},error:function(){}};(function(){function C(a,e,h){var k=[],z;for(z in a)a.hasOwnProperty(z)&&(h?k=k.concat(e(a[z])):k.push(e(a[z])));return k}function H(a,e){var h=[],k;for(k in a)a.hasOwnProperty(k)&&e(a[k])&&h.push(a[k]);return h}function E(a,e){var h=void 0,k;for(k in a)if(a.hasOwnProperty(k)&&!0===e(a[k])){h=a[k];break}return h}function U(a,e){if(N(e))return!!E(a,e);for(var h=
a.length;h--;)if(a[h]===e)return!0;return!1}function V(a,e,h){h=h||0;for(var k=a.length;h<k;h++)if(a[h]===e||N(e)&&e(a[h]))return h;return-1}function N(a){return"function"===typeof a}function S(a){return Array.isArray?Array.isArray(a):"[object Array]"===Object.prototype.toString.call(a)}function F(a){return"string"===typeof a}function I(a){return"undefined"===typeof a}function W(a){return"number"===typeof a}function X(a){if(null===a||"object"!==typeof a)return a;var e=a.constructor(),h;for(h in a)a.hasOwnProperty(h)&&
(e[h]=X(a[h]));return e}function Q(a,e){a=I(a)?{}:a;e=I(e)?{}:e;if(null===e||"object"!==typeof e)return e;var h={},k;if("object"===typeof a)for(k in a)a.hasOwnProperty(k)&&(h[k]=a[k]);for(k in e)e.hasOwnProperty(k)&&(h[k]?S(h[k])&&S(e[k])?h[k]=h[k].concat(e[k]):h[k]=Q(h[k],e[k]):h[k]=e[k]);return h}function J(a){return I(a)||null==a?!0:1>a.replace(/\s/g,"").length}function ca(a){return"mm_style"+(a?"_"+a:"")+("_"+da++)}function D(a){return a.replace(/^\s+|\s+$/gm,"")}function x(){var a=arguments,
e={},h=1;F(a[1])||(e=a[1],h=2);for(var k=a[0],a=S(a[2])?a[2]:L(a,h),h=0;h<a.length;h++)e[a[h]]=function(a){return function(){return a.apply(e,arguments)}}(k[a[h]]);return e}function Y(){function a(a){var e,k="";for(e=0;e<a;e++)k+=(16*Math.random()%16|0).toString(16);return k}return a(8)+"-"+a(4)+"-4"+a(3)+"-"+a(4)+"-"+a(12)}function O(a,e){for(var h in a)a.hasOwnProperty(h)&&e(a[h],h)}function ea(a){return function(){try{a()}catch(e){r.log(e.message||e)}}}function aa(a){var e=a.getAttribute("href");
return{hrefHasJS:/(^| )javascript:/i.test(e),sameSite:a.hostname===window.location.hostname,notRequiresReload:"_blank"===a.target||/^#|(^| )javascript: ?void/i.test(e)||!a.hasAttribute("href")}}function ba(a){for(;a&&"a"!==a.tagName.toLowerCase();)a=a.parentElement;return a}function L(a,e,h){h=I(h)?a.length:h;e=e||0;if(S(a))return Array.prototype.slice.call(a,e,h);var k=[],z=(h||0)-e;if(0<z)for(k=Array(z),h=0;h<z;h++)k[h]=a[e+h];return k}function fa(){return function(){}}function K(a){a=a||{};var e=
"";I(a.opacity)||(a.filter="alpha(opacity="+100*a.opacity+")");O(a,function(a,k){e+=k+": "+a+" !important; "});return D(e)}function ga(a,e,h){function k(b){if(!y[b]){var f=e[b],c={};try{f(c,z.requireClass,z.require),c.exports=z.options.isDlpEnabled?c.dlp||c.exports:c.basic||c.exports}catch(v){r.log("ERROR: "+v.message+" in module "+b)}g[b]&&(c.exports=c.exports.extend(g[b]));y[b]=c}return y[b]}var z=this,y,d;z.options=h||{};var g=z.options.moduleExtensions||{};this.reset=function(b){y={};d=b||{}};
z.reset(a);this.require=function(b,f){k(b);var c=y[b];return c&&c.config&&c.config.singleton?(d[b]||(d[b]=new c.exports(z.options)),d[b]):new c.exports(f)};this.requireClass=function(b){k(b);return y[b].exports};this.addModule=function(b,f){e[b]=f}}var ha=A,da=1,ia={CGApi:function(a,e,h){a.config={singleton:!0};a.exports=function(){function a(b,f,c,d){var a=g.getParam("uv",d)||{};b=D(b);a[b]=a[b]||[];if(void 0===f)f=1;else if(""===f||isNaN(f))f=0,c="NaN";a[b].push(f+(c?","+encodeURIComponent(c):""));
g.setParam("uv",a,d)}function e(b,f,c,d){var a=g.getParam("uat",c)||{};a[D(b)]=D(f+"");g.setParam("uat",a,c,d)}function y(b,f){var c=g.getParam("rul",f)||[];b=C(b,function(b){return encodeURIComponent(I(b)?"":b)}).join(",")+";";c.push(b);g.setParam("rul",c,f)}function d(b,f,c,d){var a=g.getParam("ids",c)||{};a[b+""]=f+"";g.setParam("ids",a,c,d)}var g=h("Engine");this.setAction=function(b,f,c){a(b,f,c,g.storeStrategy.request)};this.postAction=function(b,f,c){a(b,f,c,g.storeStrategy.deferredRequest)};
this.setAttr=function(b,f){e(b,f,g.storeStrategy.request)};this.storeAttr=function(b,f,c){e(b,f,g.storeStrategy.persistent,c)};this.getAttr=function(b){return(g.getParam("uat",g.storeStrategy.persistent)||{})[D(b)]};this.removeAttr=function(b){var f=g.getParam("uat",g.storeStrategy.persistent)||{};delete f[D(b)];g.setParam("uat",f,g.storeStrategy.persistent,365)};this.setId=function(b,f){d(b,f,g.storeStrategy.request)};this.storeId=function(b,f,c){d(b,f,g.storeStrategy.persistent,c)};this.removeId=
function(b){var f=g.getParam("ids",g.storeStrategy.persistent)||{};delete f[b+""];g.setParam("ids",f,g.storeStrategy.persistent,365)};this.hasActions=function(){var b=g.getParam("uv",g.storeStrategy.request)||{},f=g.getParam("uv",g.storeStrategy.deferredRequest)||{};return b&&"{}"!==JSON.stringify(b)||f&&"{}"!==JSON.stringify(f)};this.request=function(b,f){g.setParam("pageid",b.pageId,g.storeStrategy.request);b.pagePrefix&&g.setParam("pp",b.pagePrefix,g.storeStrategy.request);g.CGRequest(f)};this.setData=
function(b,f,c){g.setData(b,f,c)};this.getData=function(b){return g.getData(b)};this.clearData=function(b){g.clearData(b)};this.getServerAttrs=function(){return g.getServerAttrs()};this.setCategoryFilter=function(b,f,c){y({categoryId:b,categoryName:f,including:c?1:0},g.storeStrategy.request)};this.setProductFilter=function(b,f,c){y({categoryId:b,productId:f,including:c?1:0,isProduct:1},g.storeStrategy.request)}}},Class:function(a,e,h){e=function(){};e.extend=function(a){var k=function(){k.superclass.constructor.apply(this,
arguments);var d={};O(this,function(a,b){d[b]=a});this.base=d;return a.apply(this,arguments)},e=function(){};e.prototype=this.prototype;k.prototype=new e;k.prototype.constructor=k;k.superclass=this.prototype;k.implementation=a;k.extend=this.extend;k.inherit=this.inherit;return k};e.inherit=function(a){(a.implementation||a).call(this.prototype)};a.exports=e},Cookies:function(a,e,h){a.config={singleton:!0};a.exports=function(a){var k=this,e=a.cookieDomain,d=a.isBaseStorageSecure,g=encodeURIComponent,
b=decodeURIComponent;this.set=function(b,c,a){if(!b||!F(b))return r.error("You can't use cookies.set without specifying cookie name."),this;a=a||{};a.secure=I(a.secure)?d:a.secure;var f=";domain="+(a.domain||e),m=";path="+(a.path||"/");if(a.expires){var n=a.expires;var l=new Date;l.setTime(l.getTime()+864E5*n);n=";expires="+l.toGMTString()}else n="";a=a.secure?";secure":"";document.cookie=g(b)+"="+g(c)+f+m+n+a;return this};this.remove=function(b,c){if(!b||!F(b))return r.error("You can't use cookies.remove without specifying cookie name."),
this;c||(c={});c.expires=-1;var f=this.get(b);I(f)||this.set(b,"",c);return this};this.get=function(f){if(!f||!F(f))return r.error("You can't use cookies.get without specifying cookie name."),this;f=new RegExp("(?:^|; )"+g(f).replace(/([.$?*|{}()\[\]\\\/+^])/g,"\\$1")+"((;|$)|(=([^;]*)))");return(f=document.cookie.match(f))?b(f[4]||""):void 0};this.getWrapper=function(){return x(k,"get","set","remove")}}},Events:function(a,e,h){a.config={singleton:!1};e=e("Class").extend(function(){function a(b,f){b=
b.split(".");if(1===b.length)var c=b[0];else if(2===b.length){c=b[0];if(0===c.length||-1!==c.indexOf("*"))return!1;c=b[1]}else return!1;if(!c.length)return!1;if(-1!==c.indexOf("*"))if(f){if("*"!==c)return!1}else return!1;return b}function e(b,f,c,a){g[b]={event_data:f,callback:!0===a?c:void 0};if(d[b]){b=d[b];for(a=0;a<b.length;a++)b[a].call(y,f);N(c)&&c()}}var y=this,d={},g={};this.on=function(b,f,c){if(!F(b))return r.log("eventName is incorrect"),this;if(!a(b,!0))return r.error("'"+b+"' is incorrect for On"),
this;if(c&&(c=g[b])){try{f.apply({},[c.event_data])}catch(v){}c.callback&&c.callback()}d[b]=d[b]||[];d[b].push(f);return this};this.off=function(b,f){if(!F(b))return r.log("eventName is incorrect"),this;d[b]=d[b]||[];for(var c=d[b].length;c--;)f==d[b][c]&&d[b].splice(c,1);return this};this.trigger=function(b,f,c,d){if(!F(b))return r.log("eventName is incorrect"),this;var g=a(b,!1);if(!g)return r.error("'"+b+"' is incorrect for Trigger"),this;e(b,f,c,d);2==g.length&&e(g[0]+".*",f,c,d);return this};
this.getWrapper=function(){return x(y,{},"on","off","trigger")}});a.exports=e},EventsSite:function(a,e,h){a.config={singleton:!1};var k=e("Events").extend(function(){var a=this;this.domReady=function(){var a=!1,d=[],g=function(){document.addEventListener?(document.removeEventListener("DOMContentLoaded",b,!1),window.removeEventListener("load",b,!1)):(document.detachEvent("onreadystatechange",b),window.detachEvent("onload",b))},b=function(){if(document.addEventListener||"load"===event.type||"complete"===
document.readyState)g(),f()},f=function(){if(!a){if(!document.body)return setTimeout(f);a=!0;for(var b=0;b<d.length;b++)try{(0,d[b])()}catch(q){r.log(q)}}};if("complete"===document.readyState)f();else if(document.addEventListener)document.addEventListener("DOMContentLoaded",b,!1),window.addEventListener("load",b,!1);else{document.attachEvent("onreadystatechange",b);window.attachEvent("onload",b);var c=!1;try{c=null==window.frameElement&&document.documentElement}catch(v){}c&&c.doScroll&&function q(){if(!a){try{c.doScroll("left")}catch(m){return setTimeout(q,
50)}g();f()}}()}return function(b){b=b||function(){};if(a){try{b()}catch(q){r.log(q)}return!0}d.push(b);return!1}}();this.getWrapper=function(){return x(a,a.base.getWrapper(),"domReady")}});e=e("Events").extend(function(){var a=this,e=h("Dlp");this.domReady=function(a){return e.parentReady(a)};this.getWrapper=function(){return x(a,a.base.getWrapper(),"domReady")}});a.basic=k;a.dlp=e},EventsCampaign:function(a,e,h){a.config={singleton:!1};e=e("EventsSite").extend(function(){var a=this,e=h("Events");
this.variantJsExecuted=function(a){e.on("variantJsExecuted",function(d){a(d.elementName,d.variantName)},!0);return this};this.triggerVariantJsExecuted=function(a){e.trigger("variantJsExecuted",a);return this};this.getWrapper=function(){return x(a,a.base.getWrapper(),"variantJsExecuted")}});a.exports=e},Deferred:function(a,e,h){function k(a,d){a=a||{};for(var g in d)d.hasOwnProperty(g)&&(a[g]="object"===typeof d[g]?k(a[g],d[g]):d[g]);return a}function z(a){for(var d=[["resolve","done",[],"resolved"],
["reject","fail",[],"rejected"],["notify","progress",[]]],g="pending",b={state:function(){return g},always:function(){f.done(arguments).fail(arguments);return this},then:function(){var c=arguments;return z(function(n){for(var a=0;a<d.length;a++)(function(c,a){f[d[c][1]](function(){var l=N(a[c])&&a[c].apply(this,arguments);if(l&&N(l.promise))l.promise().done(n.resolve).fail(n.reject).progress(n.notify);else n[d[c][0]+"With"](this===b?n.promise():this,a[c]?[l]:arguments)})})(a,c);c=null}).promise()},
promise:function(c){return null!=c?k(c,b):b}},f={},c,e,q=0;q<d.length;q++)(function(a){var n=d[a],l=n[2];b[n[1]]=function(){for(var a=0;a<arguments.length;a++)(function(a){N(a)?g===n[3]?a.apply(c,e):l.push(a):a&&a.length&&"string"!==typeof a&&b[n[1]].apply(this,a)})(arguments[a]);return this};f[n[0]]=function(){f[n[0]+"With"](this===f?b:this,arguments);return this};f[n[0]+"With"]=function(b,a){if("pending"==g)for(c=b,e=a,n[3]&&(g=n[3]);l.length;)l.shift().apply(b,a);return this}})(q);b.promise(f);
a&&a.call(f,f);return f}a.exports=z},When:function(a,e,h){var k=e("Deferred");a.exports=function(){var a=0,e=N(arguments[0]),d=e?[k()]:arguments,g=Array.prototype.slice.call(d),b=g.length,f=1!==b||d[0]&&N(d[0].promise)?b:0,c=1===f?d[0]:k(),h=function(b,a,d){return function(l){a[b]=this;d[b]=1<arguments.length?Array.prototype.slice.call(arguments):l;d===n?c.notifyWith(a,d):--f||c.resolveWith(a,d)}},q;if(e){d=arguments;var m=setInterval(function(){d[0]()?c.resolve():d[1]&&N(d[1])&&d[1]()&&c.reject()},
50);c.always(function(){clearInterval(m)})}else if(1<b){var n=Array(b);e=Array(b);for(q=Array(b);a<b;a++)g[a]&&N(g[a].promise)?g[a].promise().done(h(a,q,g)).fail(c.reject).progress(h(a,e,n)):--f}f||c.resolveWith(q,g);return c.promise()}},Renderer:function(a,e,h){a.config={singleton:!1};var k=0,z=0,y=e("Class").extend(function(a){function b(){t&&(clearTimeout(t),t=null);W(u)&&(t=setTimeout(function(){c.showAll()},u))}function f(b){if(b=(b?(b.Name||b)+"":"").toLowerCase()){var c=a.getElement(b)||{},
l=c.Data;if(l)for(var f="",u="",d=0;d<l.length;d++)"Css"===l[d].Type?f=l[d].Data:"Html"===l[d].Type&&""!==D(l[d].Data)?u=l[d].Data:"Script"===l[d].Type&&(n.runElementScript(a,b,{html:u,css:f},l[d].Data),a.events.triggerVariantJsExecuted({elementName:c.Name?c.Name:"",variantName:c.VariantName?c.VariantName:""}),u=f="")}else r.log("renderElement should receive element or elementName")}var c=this,d=e("When"),g=e("Deferred"),m=h("CGApi"),n=h("Engine"),l=h("Dom"),G={},p=z++,u=7E3,t;this.hide=function(c,
a){if(!c)return r.log("You can't use renderer.hide without params"),this;-1===c.indexOf("{")&&(c+="{position:relative;left:-10000px;top:-10000px;}");a=(a||"gen_"+k++)+"_"+p;G[a]=!0;l.addCss(c,a);b();return this};this.show=function(b){if(!b)return r.log("You can't use renderer.show without params"),this;var c=b+"_"+p;if(!G[c])return r.log("ID ("+b+") you try to show is not found"),this;delete G[c];l.removeCss(c);return this};this.showAll=function(){var b=[];O(G,function(c,a){b.push(a)});l.removeMultiCss(b);
G={};t&&(clearTimeout(t),t=null);return this};this.unhideAfter=function(c){"never"===c||W(c)&&0<=c?(u=c,b()):r.log('You can use renderer.unhideAfter with number greater 0 or "never" string only.');return this};this.getContent=function(b){var c=g();b={pageId:b||(a.getPagePrefix()?"":a.getName()),pagePrefix:a.getPagePrefix()};m.request(b,function(b){b?c.resolve():c.reject()});return c.promise()};this.runVariantJs=function(b){if(0<arguments.length)f(b);else for(var c=a.getElements(),n=0;n<c.length;n++)f(c[n]);
return this};this.waitUntilDom=function(b){return d(b,n.events.domReady)};this.when=function(){return d.apply(c,arguments)}}),d=y.extend(function(a){var b=e("When"),f=h("Engine");this.waitForElement=function(c){return b(function(){return null!=document.querySelector(c)},f.events.domReady)}}),y=y.extend(function(a){var b=e("When"),f=e("Deferred"),c=h("Engine"),d=h("Dlp");this.waitForElement=function(a){var g=new f,n=!1,l=function(b){n=b};b(function(){d.checkNodeExist(a).done(l);return n},c.events.domReady).done(function(){g.resolve()}).fail(function(){d.checkNodeExist(a).done(l).then(function(b){b?
g.resolve():g.reject()},function(){g.reject()})});return g.promise()}});a.dlp=y;a.basic=d},Campaign:function(a,e,h){var k=e("Element");a.exports=function(a){function e(b){return function(c){return c.Name===b}}var d=this,g=h("Site"),b=a.Name,f=a.PagePrefix,c=h("BaseStorage",{namespace:b}),v={},q=C(a.Elements,function(b){return new k(b)}),m=a.Recommendations;this.updateData=function(b){for(var c=0;c<b.Elements.length;c++){var a=V(q,e(b.Elements[c].Name));0<=a?q[a]=new k(b.Elements[c]):q.push(new k(b.Elements[c]))}m=
b.Recommendations};this.getElements=function(){return q};this.getRecommendations=function(){return m};this.getExperience=function(){var c=g.getPageExperiences()[b],a={},f;for(f in c)c.hasOwnProperty(f)&&(a[f]=c[f]);return a};this.getElement=function(b){b||r.log("You can't use campaign.getElement without params");b=b.toLowerCase();return E(q,e(b))||null};this.getStyles=function(b){return C(q,function(c){return c.getStyles(b)},!0)};this.isDefault=function(){if(!q||0==q.length)throw Error("There is no content for campaign "+
b+".");for(var c=!0,a=0;a<q.length;a++)c=c&&"Default"===q[a].VariantName;return c};this.getName=function(){return b};this.getPagePrefix=function(){return f};this.setData=function(b,a,f){c.set(b,a,f)};this.getData=function(b){return c.get(b)};this.clearData=function(b){c.set(b,null,-1)};this.events=h("EventsCampaign");this.getContext=function(){var b={};b.scope=v;b.isDefault=function(){return d.isDefault()};b.getElements=function(){for(var b={},c=0;c<q.length;c++)b[q[c].Name]=q[c].clone();return b};
b.getElement=function(b){return(b=d.getElement(b))?b.clone():b};b.getRecommendations=function(){return C(m,X)};b.getStyles=function(b){return d.getStyles(b)};b.getExperience=function(){return d.getExperience()};b.getName=function(){return d.getName()};b.getPagePrefix=function(){return d.getPagePrefix()};b.events=d.events;b.setData=function(b,c,a){return d.setData(b,c,a)};b.getData=function(b){return d.getData(b)};b.clearData=function(b){return d.clearData(b)};return b}}},Element:function(a,e,h){function k(a){var e=
this;e.Name=a.Name;e.HTMLId=a.HTMLId;e.Order=a.Order;e.VariantName=a.VariantName;e.Data=X(a.Data);this.getStyles=function(a){return C(H(e.Data,function(d){return"Css"===d.Type&&(I(a)||d.Attrs.id===a)}),function(a){return a.Data})};this.clone=function(){return new k(e)}}a.exports=k},Site:function(a,e,h){a.config={singleton:!0};a.exports=function(){var a=this,e={},h={};this.getPageExperiences=function(){var a,g,b={};for(a in h)if(h.hasOwnProperty(a))for(g in b[a]={},h[a])h[a].hasOwnProperty(g)&&(b[a][g]=
h[a][g]);return b};this.setPageExperiences=function(a){var d;for(d in a)if(a.hasOwnProperty(d)){var b=a[d];var f=h[d];"undefined"===typeof f&&(h[d]={},f=h[d]);for(var c in b)b.hasOwnProperty(c)&&(f[c]=b[c])}return h};this.getContext=function(){var d={};d.scope=e;d.getPageExperiences=a.getPageExperiences;return d}}},Style:function(a,e,h){a.config={singleton:!0};e=e("Class").extend(function(){function a(){var b=d.createElement("style");b.type="text/css";b.media="screen";b.id=h.htmlId;var a=d.getElementsByTagName("head")[0];
a.insertBefore(b,a.lastChild);return b}function e(){var a="";O(b,function(b){a+=b});return a}var h=this,d=document;h.htmlId=ca("mm_cdApiStyleId");var g=a(),b={};this.set=function(b){(g=d.getElementById(h.htmlId))||(g=a());g.styleSheet?g.styleSheet.cssText=b:g.innerHTML=b};this.add=function(a,c){if(c){if(b[c]){r.error("Style with specified ID("+c+") already exists");return}b[c]=a}else b.nr=b.nr||"",b.nr+=a;h.set(e())};this.remove=function(){O(L(arguments),function(a){"nr"!==a&&b[a]?delete b[a]:r.error("Could not remove non-existent style "+
a+".")});h.set(e())};this.clear=function(){b={};h.set(e())}});a.exports=e},Action:function(a,e,h){a.config={singleton:!0};var k=e("Class").extend(function(){var a=this,k=h("CGApi"),d=e("Deferred");this.sendActions=function(d,b,f){for(var c=!0,e,g,m,n,l=0;l<d.length;l++)n=d[l].name,m=d[l].value,g=d[l].attribute,c&=e=d[l].postponedAction,e?a.postpone(n,m,g):a.set(n,m,g);!c||b?a.send().then(f):N(f)&&f()};this.send=function(a,b,f){var c=d();if(0<arguments.length&&a&&F(a))k.setAction(a,b,f);else if(0!==
arguments.length){r.log("You can't use action.send without setting action name");return}k.hasActions()?k.request({pageId:"mmevents"},function(b){b?c.resolve():c.reject()}):c.resolve();return c.promise()};this.postpone=function(a,b,f){if(!a||!F(a))return r.log("You can't use action.postpone without setting action name."),this;k.postAction(a,b,f);return this};this.set=function(a,b,f){if(!a||!F(a))return r.log("You can't use action.set without setting action name."),this;k.setAction(a,b,f);return this};
this.trackClicks=function(d,b,f){h("Dom").trackClicks(d,b,f,a.sendActions)};this.getWrapper=function(){return x(a,"send","postpone","set","trackClicks")}});a.exports=k},Visitor:function(a,e,h){a.config={singleton:!0};var k=e("Class").extend(function(){var a=this,d=e("Deferred"),g=h("CGApi");this.setAttr=function(b,a){g.setAttr(b,a);return this};this.storeAttr=function(b,a){g.storeAttr(b,a,365);return this};this.getAttr=function(b){return g.getAttr(b)};this.removeAttr=function(b){g.removeAttr(b);return this};
this.setId=function(b,a){g.setId(b,a);return this};this.storeId=function(b,a){g.storeId(b,a,365);return this};this.removeId=function(b){g.removeId(b);return this};this.setData=function(b,a,c){g.setData(b,a,c);return this};this.getData=function(b){return g.getData(b)};this.clearData=function(b){return g.clearData(b)};this.requestPage=function(b){var a=d();g.request({pageId:b},function(b){b?a.resolve():a.reject()});return a.promise()};this.getServerAttrs=function(){return X(g.getServerAttrs())};this.getWrapper=
function(){return x(a,"setAttr","storeAttr","getAttr","removeAttr","setId","storeId","removeId","setData","getData","clearData","requestPage","getServerAttrs")}}),z=k.extend(function(){var a=this;this.navigateTo=function(a){!F(a)||J(a)?r.log("CD API Visitor Module: You should pass targetUrl as a non-empty String to visitor.navigateTo()."):(N(window.stop)?window.stop():document.execCommand("Stop"),window.location.replace(a))};this.getWrapper=function(){return x(a,a.base.getWrapper(),"navigateTo")}}),
k=k.extend(function(){var a=this,d=h("Dlp");this.navigateTo=function(a){!F(a)||J(a)?r.log("CD API Visitor Module: You should pass targetUrl as a non-empty String to visitor.navigateTo()."):d.navigateTo(a)};this.getWrapper=function(){return x(a,a.base.getWrapper(),"navigateTo")}});a.basic=z;a.dlp=k},QuerySelector:function(a,e,h){a.config={singleton:!0};e=e("Class").extend(function(){function a(a,d){for(var c,e=[],n,l=[],g,p,u=/(\s*([+~>])\s*)?(.*?)\:(has|contains|eq)\((\"|\')?(.+?)\5\)|(\s*([+~>])\s*)?(.+)/g;null!==
(n=u.exec(a));)n&&-1<n.index&&(c=n[2]||n[8]||"",g=n[3]||n[9]||"",p=n[4]||"",n=n[6]||"",l.push({splitter:D(c),selector:D(g),queryFunction:D(p),value:D(n)}));for(g=0;g<l.length&&(a=l[g],e=b.findChildren(e,a,d),0!==a.queryFunction.length&&(c=f[a.queryFunction.toLowerCase()],e=c(e,a)),0!==e.length);g++);return e}function e(a,b){return(a.matches||a.matchesSelector||a.webkitMatchesSelector||a.mozMatchesSelector||a.msMatchesSelector).call(a,b)}function y(a){return a&&">"===a?"direct":a&&"+"===a?"next":"querySelector"}
function d(a,b,d){var c=[];a=a.querySelectorAll(d);for(d=0;d<a.length;d++)g.useZindex(a[d])&&c.push(a[d]);return b=b.concat(L(c))}var g=h("Vcb"),b=this;this.find=function(b,d){var c=[],f=Object.prototype.toString.call(b);if("[object Array]"===f||"[object NodeList]"===f||"[object HTMLCollection]"===f)return L(b);if(!F(b))return[b];b=b.split(",");for(f=0;f<b.length;f++)c=c.concat(a(D(b[f]),d));return c};var f={eq:function(a,b){return 0<a.length&&a[b.value]?[a[b.value]]:[]},contains:function(a,b){for(var c=
L(a),d=c.length-1;0<=d;d--)a=c[d].textContent||c[d].innerText,-1===a.indexOf(b.value)&&c.splice(d,1);return c},has:function(a,d){a=L(a);for(var c=a.length-1;0<=c;c--)0===b.find(d.value,a[c]).length&&a.splice(c,1);return a}};this.findChildren=function(a,b,f){var c=[];if(""===b.selector)return a;if(a.length)for(f=0;f<=a.length-f;f++){var n=a[f],l,g=[];var p=b.selector;for(l=y(b.splitter);"querySelector"!==l;){var u=p.match(/([^ >]+)( \d+)?\s*([>+]?)\s*(.*)/);p=u[4];g.push({selector:u[2]?u[1]+u[2]:u[1],
findingType:l});l=y(u[3])}p&&g.push({selector:p,findingType:l});u=g;l=S(n)?n:[n];for(n=0;n<u.length;n++)if("querySelector"===u[n].findingType){p=u[n].selector;for(var g=[],t=0;t<l.length;t++)g=d(l[t],g,p);l=g}else if("direct"===u[n].findingType){p=u[n].selector;g=[];for(t=0;t<l.length;t++)for(var k=l[t].children,h=0;k&&h<k.length;h++)1===k[h].nodeType&&e(k[h],p)&&g.push(k[h]);l=g}else if("next"===u[n].findingType)a:{p=l;g=u[n].selector;for(t=0;t<p.length;t++){for(l=p[t].nextSibling;l&&1!==l.nodeType;)l=
l.nextSibling;if(l&&e(l,g)){l=[l];break a}}l=[]}u=L(l);c=c.concat(L(u))}else u=d(f||document,[],b.selector),c=L(u);return c}});a.exports=e},Dom:function(a,e,h){a.config={singleton:!0};var k=e("Class").extend(function(){function a(a,b,c){return function(){var d=m.find(b[0]);if(d.length)return b[0]=d,a.apply(f,b),c(),!0}}function d(){G=setInterval(function(){for(var a=0;a<l.length;a++)l[a]()&&(l.splice(a,1),--a);l.length||clearInterval(G)},200);k.registerLoop(G)}function g(a,b){if(b&&!k.isVcbActive){var c=
q.autoHide(a);return function(){q.removeCss(c)}}return fa()}function b(a,b){return function(){for(var c=b&&[],d=L(arguments),n=m.find(d[0]),l=0;l<n.length;l++)if(n[l]&&n[l].tagName){d[0]=n[l];var u=a.apply(f,d);b&&c.push(u)}return c}}var f=this,c=e("Deferred"),k=h("Vcb"),q=h("DomPlain"),m=h("QuerySelector"),n=[],l=[],G,p="hide resize freeMove changeStyle guidedMove remove bringToFront changeLinkUrl insertImageBannerBelow insertImageBannerAbove insertImageBannerWithin changeImageBanner editHtml insertHtmlAbove insertHtmlBelow insertHtmlWithin makeLink".split(" "),
u=["addCss","removeCss","find"],t=["addListener","removeListener","getNodesAttribute","setNodesAttribute"];this.loop=function(b,c){return function(){var n=arguments[0],u=L(arguments),e=m.find(n);e.length?(u[0]=e,b.apply(f,u)):F(n)&&(n=g(n,!c),l.length||d(),l.push(a(b,u,n)))}};(function(a,c,d){c=c||{};O(d,function(d){c[d]=f.loop(b(a[d]))})})(q,f,p);x(q,f,u);this.addListener=function(a,b,c){a=m.find(a);for(var d=0;d<a.length;d++){var f=q.addEvent(a[d],b,c);n.push({handler:c,handlerWrapper:f})}};this.removeListener=
function(a,b,c){a=m.find(a);for(var d=0;d<a.length;d++)for(var f=0;f<n.length;f++)n[f].handler===c&&q.removeEvent(a[d],b,n[f].handlerWrapper)};this.trackClicks=f.loop(b(q.trackClicks),!0);this.removeMultiCss=q.removeMultiCss;this.getNodesAttribute=function(){var a=L(arguments);a[0]=m.find(a[0]);var d=new c;d.resolve(b(q.getNodesAttribute,!0).apply(q,a));return d.promise()};var w=f.loop(b(q.setNodesAttribute));this.setNodesAttribute=function(a,c,d,n){var l=L(arguments);"wait"===n?w.apply(f,l):(l[0]=
m.find(l[0]),b(q.setNodesAttribute).apply(q,l))};this.getWrapper=function(){var a=x(f,{},t);x(f,a,p);x(q,a,u);return a}}),z=e("Class").extend(function(){var a=this,d=h("Dlp"),e="addCss removeCss hide resize freeMove changeStyle guidedMove remove bringToFront changeLinkUrl insertImageBannerBelow insertImageBannerAbove insertImageBannerWithin changeImageBanner editHtml setNodesAttribute insertHtmlAbove insertHtmlBelow insertHtmlWithin".split(" "),b=["getNodesAttribute"],f=["addListener","removeListener"];
this.addListener=function(a,b,f){d.addListener(a,b,f)};this.removeListener=function(a,b,f){d.removeListener(a,b,f)};O(e,function(b){a[b]=d.proxy("Dom",b)});O(b,function(b){a[b]=d.proxy("Dom",b,!0)});this.trackClicks=function(a,b,f,e){d.trackClicks(a,b,f,e)};this.removeMultiCss=d.proxy("Dom","removeMultiCss");this.getWrapper=function(){var c=x(a,{},e);x(a,c,b);x(a,c,f);return c}});a.basic=k;a.dlp=z},DomPlain:function(a,e,h){a.config={singleton:!0};e=e("Class").extend(function(){function a(a,b){return window.getComputedStyle?
window.getComputedStyle(a,null)[b]:a.currentStyle?a.currentStyle[b]:a.style[b]}function e(a){return a.replace(/<script\b[^<]*(?:(?!<\/script>)<[^<]*)*<\/script>/gi,"").replace(/<title\b[^<]*(?:(?!<\/title>)<[^<]*)*<\/title>/gi,"").replace(/<link\b[^<]*>/gi,"").replace(/<meta\b[^<]*>/gi,"")}function y(a,b){var d=(a.style.cssText.replace(/[^;]$/,"$0;")+b).split(";");b={};for(var f=0;f<d.length;f++)if(d[f]){var n=d[f].split(":");b[n[0].replace(/\s/g,"")]=n[2]?n[1]+":"+n[2]:n[1]}var d="",l;for(l in b)b.hasOwnProperty(l)&&
(d+=l+":"+b[l]+"; ");c.setCssText(a,d.replace(/\s$/,""))}function d(b,c,d){var f=a(b,"position");c=c?parseInt(c,10):0;d=d?parseInt(d,10):0;if("relative"===f||"absolute"===f||"fixed"===f){var n=a(b,"left"),l=a(b,"right");"auto"===n&&"auto"!==l?c="right: "+(parseInt(l,10)-c)+"px !important; ":("auto"===n?n=c:"relative"===a(b,"position")?n=parseInt(n,10)+c:(n=parseInt(b.offsetLeft,10)+c,c=a(b,"margin-left"),"auto"!==c&&(n-=parseInt(c,10))),c="left: "+n+"px !important; ");n=a(b,"top");l=a(b,"bottom");
"auto"===n&&"auto"!==l?d="bottom: "+(parseInt(l,10)-d)+"px !important; ":("auto"===n?n=d:"relative"===a(b,"position")?n=parseInt(n,10)+d:(n=parseInt(b.offsetTop,10)+d,d=a(b,"margin-top"),"auto"!==d&&(n-=parseInt(d,10))),d="top: "+n+"px !important; ")}else f="relative",c="left: "+c+"px !important; ",d="top: "+d+"px !important; ";y(b,c+d+("position: "+f+" !important;"))}function g(a,b){I(b.imageUrl)||"img"!==a.tagName.toLowerCase()||(a.style.visibility="hidden",a.src=b.imageUrl,c.addEvent(a,"load",
function(){a.style.visibility=""}));I(b.imageAlt)||a.setAttribute("alt",e(b.imageAlt));I(b.imageTitle)||a.setAttribute("title",e(b.imageTitle))}function b(a){var b=document.createElement("img");g(b,a);if(void 0!==a.linkUrl){var c=document.createElement("a");c.setAttribute("href",a.linkUrl);c.appendChild(b)}return c||b}function f(a,b){var c=ba(b);b=void 0;if(c){var d=aa(c);if(!d.sameSite){a.originalPreventDefault=a.originalPreventDefault||a.preventDefault;a.preventedByClientsCode=a.preventedByClientsCode||
a.defaultPrevented&&!a.preventedByCdApiCode;a.preventDefault=function(){a.preventedByClientsCode=!0;a.originalPreventDefault()};a.originalPreventDefault();a.preventedByCdApiCode=!0;var f=!1;b=function(){f||a.preventedByClientsCode||(d.hrefHasJS?(new Function(c.getAttribute("href"))).call(window):d.notRequiresReload||window.location.assign(c.href),f=!0)};setTimeout(b,2E3)}}return b}var c=this,v=h("Vcb"),q=h("Style"),m=h("QuerySelector");this.setCssText=function(a,b){a.style.cssText=b};this.addCss=
function(a,b){if(!S(a)&&!F(a))return r.log("You try call dom.addCss with wrong arguments."),this;0===a.length&&r.log("WARNING: You add empty css.");a.join&&(a=a.join("\n"));q.add(a,b);return this};this.removeCss=function(a){if(!a)return r.log("You can't use dom.removeCss without params"),this;q.remove(a);return this};this.removeMultiCss=function(a){q.remove.apply(q,a);return this};this.getStyle=a;this.find=m.find;this.updateElementStyle=y;this.addEvent=function(a,b,c){var d=function(b){b=b||window.event;
!b.target&&b.srcElement&&(b.target=b.srcElement);return c.call(a,b)};a.addEventListener?a.addEventListener(b,d,!1):a.attachEvent&&a.attachEvent("on"+b,d);return d};this.removeEvent=function(a,b,c){a.removeEventListener?a.removeEventListener(b,c):a.detachEvent&&a.detachEvent("on"+b,c)};this.addClass=function(a,b){b=D(b);var c=D(a.getAttribute("class")||"");~c.indexOf(b)||a.setAttribute("class",D(c?c+" "+b:b))};this.hide=function(a){y(a,"visibility: hidden !important;")};this.show=function(a){y(a,"visibility: visible !important;")};
this.resize=function(a,b,c,f,e){b=parseInt(b,10);c=parseInt(c,10);y(a,"width: "+b+"px !important; height: "+c+"px !important;");(f||e)&&d(a,f,e)};this.freeMove=d;this.changeStyle=y;this.guidedMove=function(a,b){if(0<=b){var c=a.parentElement;c.removeChild(a);var d=c.children;b<d.length?c.insertBefore(a,d[b]):c.appendChild(a)}};this.remove=function(a){var b=a.parentElement;b&&b.removeChild(a)};this.bringToFront=function(b,c){if("undefined"===typeof c){for(var d=0,f=document.querySelectorAll("*"),e=
f.length,g=0;g<e;g++)if(c=parseInt(a(f[g],"z-index"),10),!isNaN(c)&&d<c&&v.useZindex(f[g])&&(d=c),v.isVcbActive&&d>=v.maxZindex){d=v.maxZindex-11;break}c=d+10}d=a(b,"position");y(b,"z-index: "+c+" !important; position: "+("static"===d||"auto"===d?"relative":d)+" !important;")};this.changeLinkUrl=function(a,b){c.setNodesAttribute(a,"href",b)};this.insertImageBannerAbove=function(a,c){c=b(c);a.parentElement.insertBefore(c,a)};this.insertImageBannerBelow=function(a,c){c=b(c);a.parentElement.insertBefore(c,
a.nextSibling)};this.insertImageBannerWithin=function(a,c){c=b(c);a.appendChild(c)};this.changeImageBanner=function(a,b){if("a"===a.tagName.toLowerCase()){void 0!==b.linkUrl&&a.setAttribute("href",b.linkUrl);a=a.children;for(var c=0;c<a.length;c++)"img"===a[c].tagName.toLowerCase()&&g(a[c],b)}else"img"===a.tagName.toLowerCase()&&(g(a,b),void 0!==b.linkUrl&&"a"===a.parentElement.tagName.toLowerCase()&&a.parentElement.setAttribute("href",b.linkUrl))};this.editHtml=function(a,b){a.innerHTML=e(b)};this.makeLink=
function(a,b,c){if("a"===a.tagName.toLowerCase())var d=a;else d=document.createElement("a"),a.parentElement.insertBefore(d,a),d.appendChild(a);d.setAttribute("href",b);I(c)||d.setAttribute("target",c)};this.setNodesAttribute=function(a,b,c){a.setAttribute(b,c)};this.getNodesAttribute=function(a,b){return a.getAttribute(b)};this.insertHtmlAbove=function(a,b){var c=document.createElement("div");a.parentElement.insertBefore(c,a);c.outerHTML=e(b)};this.insertHtmlBelow=function(a,b){var c=document.createElement("div");
a.parentElement.insertBefore(c,a.nextSibling);c.outerHTML=e(b)};this.insertHtmlWithin=function(a,b){var c=document.createElement("div");a.appendChild(c);c.outerHTML=e(b)};this.autoHide=function(a){a=a.replace(/:eq\(\d*\)/gmi,"");var b=Y();c.addCss(a+"{visibility: hidden;}",b);return b};this.trackClicks=function(a,b,d,e){v.isVcbActive?v.registerClickAction(a,b,d):(a["data-mm-events-ref"]||(a["data-mm-events-ref"]={lockFuncs:[]},c.addEvent(a,"click",function(a){for(var b=this["data-mm-events-ref"].lockFuncs,
c=[],d=0;d<b.length;d++){var g=b[d]();if(g){var u=g[0];var p=u;var h=a;p=h.target===this?!1:F(h.data)&&U(h.data.split(","),p);p||(c.push({name:u,value:g[1],attribute:g[2],postponedAction:I(g[3])?!0:g[3]}),g=a.data&&F(a.data)?a.data.split(","):[],U(g,u)||(g.push(u),a.data=g.join()))}}if(c.length){var d=ba(this),b=!1,k;if(d){if(!(k=aa(d)).sameSite||k.notRequiresReload)b=!0}else k=this.nodeName.toLowerCase(),d=this.getAttribute("type"),("input"===k||"button"===k)&&d&&"submit"===d.toLowerCase()||(b=!0);
e(c,b,f(a,this))}})),a["data-mm-events-ref"].lockFuncs.push(function(){return[b.name,b.value,b.attribute,b.postponedAction]}))}});a.exports=e},BaseWidget:function(a,e,h){a.config={singleton:!1};e=e("Class").extend(function(a){function e(a,b){for(;a&&a.parentNode;)if(a=a.parentNode,a===b)return!0;return!1}function k(){function a(a){return!a||!W(a.displayedCount)||a.displayedCount>=b.showsCount?1:a.displayedCount+1}var b=m.options.showFrequency;if(!0!==b.always){var c=new Date,d=m.getWidgetData(),f=
d.persistent,d=d.session,e;b.showsInterval&&"session"===b.showsInterval&&(e={lastShown:c,displayedCount:a(d)});c={lastShown:c,wasDismissed:f&&f.wasDismissed||!1,displayedCount:a(f)};m.setWidgetData(c,e)}}function d(){var a=m.getWidgetData(),b=a.persistent;m.setWidgetData({lastShown:b&&b.lastShown,wasDismissed:!0,displayedCount:b&&b.displayedCount},a.session)}function g(){function a(){var a=f.lastShown&&f.lastShown.getTime();if(!J(g)){if("session"===g)return!d.session;if("campaign"===g)return!d.persistent;
var b=new Date,e=b.getMonth(),b=b.getFullYear();if(e={hour:36E5,day:864E5,week:6048E5,month:864E5*(new Date(b,e,0)).getDate()}[g])return c-a>e}}var b=m.options.showFrequency;if(!(!0!==b.always&&b.showsInterval||b.neverAfterDismiss))return!0;var c=new Date,d=m.getWidgetData(),f=d.persistent,e=d.session;if(f&&!0===b.neverAfterDismiss&&!0===f.wasDismissed)return!1;if(!0===b.always||!b.showsInterval)return!0;var g=D(b.showsInterval.toLowerCase()),b=b.showsCount;if(!J(g)&&b&&W(b)){if("session"===g&&!d.session||
!d.persistent)return!0;var h=a();return"session"===g?e.displayedCount<b:f.displayedCount<b||h}}var b=h("CGApi"),f=h("Engine").events,c=h("Dom"),v=h("DomPlain"),q=h("QuerySelector"),m=this,n=!1,l=[],r=[];m.target=document.body;m.selectors={guidAttr:"data-vcb-me-guid",wrapper:"vcb-me-wrapper",overlay:"vcb-me-overlay",contentWrapper:"vcb-me-content-wrapper",content:"vcb-me-content",contentInner:"vcb-me-content-inner",dismiss:"vcb-me-dismiss",pointer:"vcb-me-pointer"};m.type="BaseWidget";m.wrapper=null;
m.contentWrapper=null;m.content=null;m.setWidgetData=function(a,c){var d=m.options.guid;a&&b.setData(d+"persistData",JSON.stringify(a),365);c&&b.setData(d+"sessionData",JSON.stringify(c),0)};m.getWidgetData=function(){var a=m.options.guid,c={persistent:void 0,session:void 0};if(!J(a)){var d=b.getData(a+"sessionData"),a=b.getData(a+"persistData");J(a)||(c.persistent=JSON.parse(a),c.persistent.lastShown=new Date(c.persistent.lastShown));J(d)||(c.session=JSON.parse(d),c.session.lastShown=new Date(c.session.lastShown))}return c};
m.clearWidgetData=function(){var a=m.options.guid;J(a)||(b.clearData(a+"persistData"),b.clearData(a+"sessionData"))};m.validateOptions=function(a){var b=[];a.appearance.name||b.push("Can't create widget! Name parameter required!");a.guid||b.push("Can't create widget! Guid parameter required!");a.content||b.push("Can't create widget! Content is required!");if(b.length)throw Error(b.join("\n"));};m.addClassesAndIdContentElements=function(){for(var a=m.getContentWrapper(),b=m.options,a=a.firstChild;null!==
a&&1!==a.nodeType;)a=a.nextSibling;if(a){a.id||(a.id=b.guid);v.addClass(a,m.selectors.content);if(!J(b.closeEvent.dismissElements)){var c=q.find(b.closeEvent.dismissElements,a);for(b=0;b<c.length;b++)v.addClass(c[b],m.selectors.dismiss)}for(b=a.lastChild;null!==b&&1!==b.nodeType;)b=b.previousSibling;!b||c&&~V(c,b)||v.addClass(b,m.selectors.contentInner)}};m.getWrapper=function(){if(e(m.wrapper,m.target))return m.wrapper;var a=q.find("["+m.selectors.guidAttr+'="'+m.options.guid+'"]',m.target)[0];if(a)return a};
m.wrapperFor=function(a){return function(){if(!e(m[a],m.target)){var b=m.getWrapper();m[a]=q.find("."+m.selectors[a],b)[0]}return m[a]}};m.getContentWrapper=m.wrapperFor("contentWrapper");m.getContent=m.wrapperFor("content");m.bindWidgetShowEvents=function(){var a=function(){g()&&m.show()},b=m.options.displayEvent,c;!0===b.onPageLoad&&f.domReady(a);if(!J(b.initAttachedTo)){var d=q.find(b.initAttachedTo);for(c=0;c<d.length;c++)!0===b.onClick&&v.addEvent(d[c],"click",a),!0===b.onMouseOver&&v.addEvent(d[c],
"mouseover",a),!0===b.onMouseOut&&v.addEvent(d[c],"mouseout",a)}if(b.delay){var e=1E3*parseInt(b.delay,10);if(b.startAfterIdle){var h;v.addEvent(document,"ontouchstart"in window?"touchmove":"mousemove",function(){window.clearTimeout(h);h=window.setTimeout(a,e)})}else window.setTimeout(a,e)}b.onLosePageFocus&&(v.addEvent(window,"blur",a),v.addEvent(window,"pagehide",a));b.onViewportMouseOut&&v.addEvent(document,"mouseout",function(a){(a=a.relatedTarget||a.toElement)&&"html"!==a.nodeName.toLowerCase()||
g()&&m.show()});if(!J(b.onCustomEvent))f.on(b.onCustomEvent,a)};m.bindDismissEvents=function(){var a=m.getWrapper(),b=m.options.closeEvent;if(b.onDismissButton&&!J(b.dismissElements))for(a=q.find(b.dismissElements,a),b=0;b<a.length;b++)v.addEvent(a[b],"click",m.dismiss)};m.bindCloseEvents=function(){function a(a){var c=q.find(m.options.displayEvent.initAttachedTo||""),d=m.getWrapper(),d=q.find("*:not(."+m.selectors.overlay+")",d);if(~V(c,a.target)||~V(d,a.target))return!1;b()}var b=m.hide;m.options.closeEvent.onClickOutside&&
(v.addEvent(document,"click",a),v.addEvent(window,"keydown",function(a){27===(I(a.which)?a.keyCode:a.which)&&b()}))};m.show=function(){var a=m.getWrapper();v.show(a);for(a=0;a<l.length;a++)l[a].call(null);n=!0};m.hide=function(){var a=m.getWrapper();c.hide(a);n=!1};m.dismiss=function(){m.hide();for(var a=0;a<r.length;a++)r[a].call(null)};m.destroy=function(){var a=m.getWrapper();a&&a.parentNode&&a.parentNode.removeChild(a)};m.getOptions=function(){return m.options};m.isShown=function(){return n};
m.subscribeFunctionOnImgsLoads=function(a){for(var b=q.find("img"),c=0;c<b.length;c++)v.addEvent(b[c],"load",a)};m.init=function(){m.options=m.mergeWithDefaultWidgetOptions(a);m.validateOptions(m.options);r.push(d);l.push(k);m.createWidgetDom();m.bindWidgetShowEvents()}});a.exports=e},Lightbox:function(a,e,h){a.config={singleton:!1};e=e("BaseWidget").extend(function(){function a(){var a=b.getOverlay(),d=b.options.appearance,f={display:"block",position:"fixed",top:"0px",left:"0px",height:"100%",width:"100%"};
d.fadeEnabled?(f["background-color"]=d.fadeColor,f.opacity=parseFloat(d.opacity)):f.opacity=0;g.updateElementStyle(a,K(f))}function e(){var a=b.getContentWrapper(),d=b.options.appearance,f={};f["background-color"]=d.backgroundColor;f.position="fixed";d.autofit?(f.display="inline-block",f.width="auto",f.height="auto"):(f.width=d.width,f.height=d.height);g.updateElementStyle(a,K(f))}function r(){var a=b.getContentWrapper();g.updateElementStyle(a,K({top:0,left:0}));var d={},f=window.innerWidth||document.documentElement.clientWidth||
document.body.clientWidth,e=window.innerHeight||document.documentElement.clientHeight||document.body.clientHeight,h=parseInt(g.getStyle(a,"width"),10),k=parseInt(g.getStyle(a,"height"),10),r=(e<k?e-30:k)/2;d.position=e<k+r-60?"absolute":"fixed";d.top="50%";d.left="50%";d["margin-top"]=-1*r+"px";d["margin-left"]=(f<h?f:h)/2*-1+"px";g.updateElementStyle(a,K(d))}var d=h("Dom"),g=h("DomPlain"),b=this,f=b.base;b.type="Lightbox";b.widgetOverlay=null;b.getOverlay=b.wrapperFor("overlay");b.mergeWithDefaultWidgetOptions=
function(a){return Q({appearance:{backgroundColor:"#FFFFFF",fadeEnabled:!0,fadeColor:"#000000",opacity:.8,autofit:!0},displayEvent:{},closeEvent:{onDismissButton:!0,onClickOutside:!0},showFrequency:{always:!0,neverAfterDismiss:!0}},a)};b.show=function(){a();e();r();b.subscribeFunctionOnImgsLoads(r);f.show()};b.createWidgetDom=function(){b.wrapper=document.createElement("div");b.wrapper.setAttribute(b.selectors.guidAttr,b.options.guid);g.addClass(b.wrapper,b.selectors.wrapper);d.hide(b.wrapper);b.target.appendChild(b.wrapper);
b.widgetOverlay=document.createElement("div");g.addClass(b.widgetOverlay,b.selectors.overlay);b.wrapper.appendChild(b.widgetOverlay);a();d.bringToFront(b.widgetOverlay);b.contentWrapper=document.createElement("div");g.addClass(b.contentWrapper,b.selectors.contentWrapper);b.wrapper.appendChild(b.contentWrapper);b.contentWrapper.innerHTML=b.options.content;b.addClassesAndIdContentElements();e();d.bringToFront(b.contentWrapper);b.bindCloseEvents();b.bindDismissEvents()};b.init()});a.exports=e},Notification:function(a,
e,h){a.config={singleton:!1};e=e("BaseWidget").extend(function(){var a=h("Dom"),e=h("DomPlain"),r=h("QuerySelector"),d=this,g=d.base;d.type="Notification";d.mergeWithDefaultWidgetOptions=function(a){return Q({appearance:{backgroundColor:"#FFFFFF"},displayEvent:{},closeEvent:{onDismissButton:!0},showFrequency:{always:!0}},a)};d.createWidgetDom=function(){d.wrapper=document.createElement("div");d.wrapper.setAttribute(d.selectors.guidAttr,d.options.guid);e.addClass(d.wrapper,d.selectors.wrapper);a.hide(d.wrapper);
d.target.appendChild(d.wrapper);d.contentWrapper=document.createElement("div");e.addClass(d.contentWrapper,d.selectors.contentWrapper);d.contentWrapper.innerHTML=d.options.content;d.wrapper.appendChild(d.contentWrapper);d.addClassesAndIdContentElements();d.bindCloseEvents();d.bindDismissEvents()};d.show=function(){var a=d.getWrapper(),f,c=d.options.appearance;if(!J(c.insertWithin))(f=r.find(c.insertWithin)[0])&&f.appendChild(a);else if(!J(c.insertAbove))(f=r.find(c.insertAbove)[0])&&f.parentElement.insertBefore(a,
f);else if(!J(c.insertBelow))(f=r.find(c.insertBelow)[0])&&f.parentElement.insertBefore(a,f.nextSibling);else if(!J(c.insertWithReplace)&&(f=r.find(c.insertWithReplace)[0])){for(;f.hasChildNodes();)f.removeChild(f.firstChild);f.appendChild(a)}if(f){a=d.getContentWrapper();f=d.getContent();var c=d.options.appearance,h={},k={};k["background-color"]=c.backgroundColor;c.autofit?(h.display="inline-block",h.width="auto",h.height="auto"):(h.width=c.width,h.height=c.height,h["margin-left"]="auto",h["margin-right"]=
"auto",k.width="100%",k.height="100%");e.updateElementStyle(f,K(k));e.updateElementStyle(a,K(h));g.show()}};d.hide=function(){var a=d.getWrapper();d.target.appendChild(a);g.hide()};d.init()});a.exports=e},Callout:function(a,e,h){a.config={singleton:!1};e=e("BaseWidget").extend(function(){function a(a){return"top"===a}function e(a){return"bottom"===a}function r(a){return"left"===a}function d(a){return"right"===a}function g(a){return"center"===a}function b(a){a=a.getBoundingClientRect();var b=I(window.pageXOffset)?
document.documentElement.scrollLeft:window.pageXOffset,c=I(window.pageYOffset)?document.documentElement.scrollTop:window.pageYOffset,d=a.top+c,f=a.left+b,c=a.bottom+c,b=a.right+b;return{top:d,left:f,bottom:c,right:b,width:a.width||b-f,height:a.height||c-d}}function f(a){var b=(a||"").split(" ");a=D(b[0]||"left").toLowerCase();b=D(b[1]||"top").toLowerCase();return{side:a,part:b}}function c(a){var b=(a||"").split(" ");a=parseInt(b[0]||0,10);b=parseInt(b[1]||0,10);return{side:a,part:b}}function v(h,
k,l,n){function m(){r(p.part)?t.left=q.part:g(p.part)?t.left=w.width/2-M/2+q.part:d(p.part)&&(t.left=w.width-M-q.part)}function u(){a(p.part)?t.top=q.part:g(p.part)?t.top=w.height/2-B/2+q.part:e(p.part)&&(t.top=w.height-B-q.part)}var t={},p=f(l),q=c(n),w={};if("page"===k||"viewport"===k)w.top=w.right=w.bottom=w.left=0,"page"===k?(l=b(document.body),w.width=l.width,w.height=l.height):(w.width=window.innerWidth||document.documentElement.clientWidth||document.body.clientWidth,w.height=window.innerHeight||
document.documentElement.clientHeight||document.body.clientHeight);if(h=A.find(h)[0]){h=b(h);var M=h.width,B=h.height;r(p.side)?(u(),t.left=q.side):d(p.side)?(u(),t.left=w.width-M-q.side):e(p.side)?(m(),t.top=w.height-B-q.side):a(p.side)?(m(),t.top=q.side):g(p.side)&&g(p.part)&&(t.left=w.width/2-M/2+q.side,t.top=w.height/2-B/2+q.part);t.position="viewport"===k?"fixed":"absolute";return t}}function q(h,k,n,m){function u(){a(t.part)?q.top=v.top-w.part:g(t.part)?q.top=v.top+v.height/2-B/2+w.part:e(t.part)&&
(q.top=v.bottom-B+w.part)}function p(){r(t.part)?q.left=v.left-w.part:g(t.part)?q.left=v.left+v.width/2-M/2+w.part:d(t.part)&&(q.left=v.right-M+w.part)}var q={},t=f(n),w=c(m),v={};if(k){k=A.find(k)[0];if(!k)return;v=b(k)}if(h=A.find(h)[0]){k=b(h);var M=k.width,B=k.height;h=h.offsetParent||document.body;k=l.getStyle(h,"position");if("relative"===k||"absolute"===k||"fixed"===k)h=b(h),v.top-=h.top,v.left-=h.left,v.right=v.left+v.width,v.bottom=v.top+v.height;r(t.side)?(u(),q.left=v.left-M-w.side):d(t.side)?
(u(),q.left=v.right+w.side):a(t.side)?(p(),q.top=v.top-B-w.side):e(t.side)?(p(),q.top=v.bottom+w.side):g(t.side)&&g(t.part)&&(q.left=v.left+v.width/2-M/2+w.part,q.top=v.top+v.height/2-B/2+w.part);q.position="absolute";return q}}function m(){function c(a,b){b=b||"px";var c=["z-index"],d={},f;for(f in a)if(a.hasOwnProperty(f)){var e=a[f];W(e)&&0!==e&&!~V(c,f)&&(e+=b);d[f]=e}return d}function h(a){return{top:"bottom",bottom:"top",left:"right",right:"left"}[a]}function k(a,b){l.updateElementStyle(a,K(b));
l.updateElementStyle(a.children[0],K({width:0,height:0}))}function m(c,k,l,m){function n(b){var f,k="side"===b?"part":"side";a(B[b])||e(B[b])?f=0>c.top&&t.bottom+p.height<u.height||c.top+p.height>u.height&&0<t.top-p.height?h(B[b]):B[b]:d(B[b])||r(B[b])?f=0>c.left&&t.right+p.width<u.width||c.left+p.width>u.width&&0<t.left-p.width?h(B[b]):B[b]:g(B[b])&&(f=a(B[k])||e(B[k])?0>c.left?"right":c.left+p.width>u.width?"left":B[b]:r(B[k])||d(B[k])?0>c.top?"top":c.top+p.height>u.height?"bottom":B[b]:B[b]);return f}
var u={width:window.innerWidth||document.documentElement.clientWidth||document.body.clientWidth,height:window.innerHeight||document.documentElement.clientHeight||document.body.clientHeight},M=I(window.pageXOffset)?document.documentElement.scrollLeft:window.pageXOffset,q=I(window.pageYOffset)?document.documentElement.scrollTop:window.pageYOffset,p=Q({},b(l));l=A.find(m)[0];var t=b(l),B=f(k);c=Q({},c);c.top-=q;c.left-=M;p.top-=q;p.left-=M;p.bottom-=q;p.right-=M;k=n("side");M=n("part");return k+" "+
M}var u=p.getContentWrapper(),z=p.options.appearance,y=p.options.appearance.position,G=y.at;var x={};l.updateElementStyle(u,K({top:0,left:0}));if("page"===y.relativeTo||"viewport"===y.relativeTo)x=v(u,y.relativeTo,G,y.offset),x=c(x);else if(!J(y.relativeTo)){x=q(u,y.relativeTo,G,y.offset);if(y.viewportDetection){var D=m(x,G,u,y.relativeTo);D!==G&&(G=D,x=q(u,y.relativeTo,G,y.offset))}x=c(x)}l.updateElementStyle(u,K(x));(function(g,m,t){function M(a,b){var c=a;b&&2*a>b&&(c=b-a,c=0>c?0:c);return c}var B=
p.getContent(),v=p.getPointer(),w=v&&v.children[0],y=!1,P=1,Z=1,x=0,G=0,D="0 ",T={},I={width:0,height:0,"border-top":"none","border-bottom":"none","border-left":"none","border-right":"none"};if(m){var C=f(g),J=b(u);var H=C.part;"page"===t||"viewport"===t?(F(m)?(t=f(m),g=t.side,H=t.part,y=g!==C.side&&g!==C.part):(g=C.side,m=g+" "+H),Z=-1):(g=h(C.side),m=g+" "+H,P=-1,t=A.find(t)[0],T=b(t));var E=function(b){b=a(b)||e(b)?"width":r(b)||d(b)?"height":void 0;b=Math.ceil(3*Math.log(J[b]));return 7>b?7:b}(g);
t=function(a){var b=E+"px solid "+z.backgroundColor,c=E+"px solid transparent";return Q(I,{top:{"border-bottom":b,"border-left":c,"border-right":c},bottom:{"border-top":b,"border-left":c,"border-right":c},right:{"border-top":c,"border-bottom":c,"border-left":b},left:{"border-top":c,"border-bottom":c,"border-right":b}}[a])}(g);l.updateElementStyle(v,K(t));t=b(v);C=a(H)||e(H)?M(t.height,T.height):0;T=r(H)||d(H)?M(t.width,T.width):0;a(g)?(G=t.height,D+=-T):e(g)?(G=t.height*Z*P,D+=-T):r(g)?(x=t.width,
D+=-C):d(g)&&(x=t.width*Z*P,D+=-C);y||n.freeMove(u,x,G);m=c(q(v,B,m,D));l.updateElementStyle(v,K(m));w&&(v=w.children[0],m=Math.sqrt(2*Math.pow(E,2)),B={margin:0,padding:0,"box-shadow":l.getStyle(B,"box-shadow"),transform:"rotate(45deg)",position:"absolute","z-index":-1,width:m,height:m},P={position:"absolute",overflow:"hidden",top:-E,left:-E,width:2*t.width,height:2*t.height},x=E-m/2+t.width/2,G=-E-t.width/2,D=E-m/2+t.height/2,t=-E-t.height/2,a(g)?(B.top=2*E-m/2,B.left=x,P.left=G):e(g)?(B.top=-m/
2,B.left=x,P.left=G):r(g)?(B.top=D,B.left=2*E-m/2,P.top=t):d(g)&&(B.top=D,B.left=-m/2,P.top=t),l.updateElementStyle(w,K(c(P))),l.updateElementStyle(v,K(c(B))))}else k(v,I)})(G,y.pointer,y.relativeTo)}var n=h("Dom"),l=h("DomPlain"),A=h("QuerySelector"),p=this,u=p.base;p.type="Callout";p.pointer=null;p.mergeWithDefaultWidgetOptions=function(a){return Q({appearance:{backgroundColor:"#FFFFFF",autofit:!0,position:{at:"top left",relativeTo:"viewport"}},displayEvent:{},closeEvent:{onDismissButton:!0},showFrequency:{always:!0}},
a)};p.getPointer=p.wrapperFor("pointer");p.createWidgetDom=function(){p.wrapper=document.createElement("div");p.wrapper.setAttribute(p.selectors.guidAttr,p.options.guid);l.addClass(p.wrapper,p.selectors.wrapper);n.hide(p.wrapper);p.target.appendChild(p.wrapper);p.contentWrapper=document.createElement("div");l.addClass(p.contentWrapper,p.selectors.contentWrapper);p.contentWrapper.innerHTML=p.options.content;p.wrapper.appendChild(p.contentWrapper);n.bringToFront(p.contentWrapper);p.addClassesAndIdContentElements();
p.pointer=document.createElement("span");l.addClass(p.pointer,p.selectors.pointer);l.updateElementStyle(p.pointer,K({width:0,height:0,margin:0,padding:0,display:"inline-block"}));p.contentWrapper.appendChild(p.pointer);var a=document.createElement("div");p.pointerShadow=document.createElement("div");p.pointerShadow.appendChild(a);p.pointer.appendChild(p.pointerShadow);p.bindCloseEvents();p.bindDismissEvents()};p.show=function(){var a=p.getContentWrapper(),b=p.getContent(),c=p.options.appearance,d=
{},f={};f["background-color"]=c.backgroundColor;c.autofit?(d.display="inline-block",d.width="auto",d.height="auto"):(d.width=c.width,d.height=c.height,f.width="100%",f.height="100%");f=Q(d,f);l.updateElementStyle(b,K(f));l.updateElementStyle(a,K(d));m();p.subscribeFunctionOnImgsLoads(m);u.show()};p.init()});a.exports=e},Widgets:function(a,e,h){a.config={singleton:!0};e=e("Class").extend(function(){var a=this;this.createLightbox=function(a,e){a.guid=e;h("Lightbox",a)};this.createNotification=function(a,
e){a.guid=e;h("Notification",a)};this.createCallout=function(a,e){a.guid=e;h("Callout",a)};this.getWrapper=function(){return x(a,"createLightbox","createCallout","createNotification")}});a.exports=e},Dlp:function(a,e,h){a.config={singleton:!0};var k=e("Class").extend(function(a){function k(a){if(a.origin===l){a=a.data;try{var b=JSON.parse(a)}catch(w){r.log("Can not parse message,\nbecause of: "+w.message+"\nerror with object:",a)}if(b)if(b.request)try{b.command&&p[b.command](b)}catch(w){r.log('Can not execute "'+
b.command+'" request command,\nbecause error occurred: '+w.message)}else if(b.error&&r.log(b.error),a=m[b.hash]){try{b.error?a.reject({error:b.error,data:b.data}):a.resolve(b.data)}catch(w){r.log(w)}delete m[b.hash]}}}function d(a,b){return{hash:Y(),command:a,data:b}}function g(a){try{window.parent.postMessage(JSON.stringify(a),l)}catch(w){r.log("Can not send event through post message,\nbecause of: "+w.message+"\nerror with object:",a);var b=m[a.hash];b&&(b.reject({error:w,data:void 0}),delete m[a.hash])}}
function b(a){var b=new v;m[a.hash]=b;g(a);return b.promise()}function f(a,b,c){return function(){for(var f={},e=0;e<c.length;e++)f[c[e]]=arguments[e];return a(d(b,f))}}var c=this,v=e("Deferred"),q=h("Action"),m={},n=new v,l=a.dlpOrigin,z={},p={console:function(a){a=a.data;r[a.method](a.message)},raiseEvent:function(a){z[a.data.handlerHash]()},"Action.sendActions":function(a){a=a.data.args;var b=a[2];a[2]=function(){g(d("runCallback",{handler:b}))};q.sendActions.apply(q,a)}};this.parentReady=function(a){n.done(ea(a));
return"resolved"===n.state()};this.proxy=function(a,c,f){return function(){var e={args:L(arguments),promised:f};return(f?b:g)(d(a+"."+c,e))}};this.trackClicks=function(a,b,c,f){g(d("Dom.trackClicks",{args:[a,b,c]}))};this.addListener=function(a,b,c){a=d("Dom.addListener",{selector:a,eventName:b});for(e in z)if(z.hasOwnProperty(e)&&z[e]===c){var f=e;break}var e=a.data;f?e.handlerHash=f:(e.handlerHash=Y(),z[e.handlerHash]=c);g(a)};this.removeListener=function(a,b,c){a=d("Dom.removeListener",{selector:a,
eventName:b});for(var f in z)if(z.hasOwnProperty(f)&&z[f]===c){a.data.handlerHash=f;g(a);break}};this.checkNodeExist=f(b,"checkNodeExist",["selector"]);this.navigateTo=f(g,"navigateTo",["url"]);addEventListener?addEventListener("message",k,!1):attachEvent("onmessage",k);n=b(d("parentReady"));this.isDlpEnabled=function(){return!0};this.getWrapper=function(){return x(c,"isDlpEnabled")}});a.basic=function(){var a=this;this.getWrapper=function(){return x(a,"isDlpEnabled")};this.isDlpEnabled=function(){return!1}};
a.dlp=k},Modules:function(a,e,h){var k=e("Class");h=k.extend(function(){var a=this,h={cgapi:{},campaign:{alias:"Campaign",args:["campaignData"]},site:{alias:"Site"},renderer:{alias:"Renderer",args:["campaign"]},element:{},html:{},css:{},Deferred:{},when:{},events:{alias:"Events"},actions:{alias:"Action"},visitor:{alias:"Visitor"},modules:{alias:"Modules"},dom:{alias:"Dom"},cookies:{alias:"Cookies"},style:{alias:"Style"},recommendations:{}},d=[],g=[],b={};this.define=function(a,b,h){if(!a||"string"!==
typeof a)return r.log("Invalid module alias ( "+a+" )."),this;if(d[a])return d[a].reserved?r.log("Reserved name can not be used ( "+a+" )."):r.log("Module with this alias already defined  ( "+a+" )."),this;"function"===typeof b?(h=b,b={}):"string"===typeof b?b={extend:b}:b&&"object"===typeof b||(b={});"undefined"===typeof b.singleton&&(b.singleton=!0);"undefined"===typeof b.autoDefine&&(b.autoDefine=!0);if("undefined"!==typeof b.extend&&("string"!==typeof b.extend||!b.extend))return r.log("Invalid parent alias ( "+
b.extend+" )"),this;if(b.extend&&(!d[b.extend]||d[b.extend].reserved&&!d[b.extend].standard))return r.log("Parent module is not defined ( "+b.extend+" )"),this;if(!h||"function"!==typeof h)return r.log("Invalid module function ( "+a+" )."),this;if(b.extend){var c=d[b.extend];if(c.reserved&&c.standard){var f=e(c.standard);"undefined"===typeof f.extend&&(f=k.extend(f));var n=c.args}else f=c.func;h=f.extend(h)}else h=k.extend(h);d[a]={func:h,extend:b.extend,extendArgs:n,reserved:!1,singleton:b.singleton,
autoDefine:b.autoDefine};!0===b.autoDefine&&g.push(a);return this};this.require=function(a){if(a&&"string"===typeof a){var c=d[a];if(c&&!0!==c.reserved){a=c.instance;if(!a||!c.singleton)if(c.extendArgs){var f=[];for(g in c.extendArgs)c.extendArgs.hasOwnProperty(g)&&f.push(b[c.extendArgs[g]]);var e=function(){e.prototype=c.func.prototype;return c.func.apply(this,f)};a=new e}else a=new c.func;if(c.singleton){c.instance=a;var g={};var h=a,k;for(k in h)h.hasOwnProperty(k)&&(g[k]="function"===typeof h[k]?
function(a){return function(){return h[a].apply(h,arguments)}}(k):h[k]);a=g}return a}r.log("Module is not registered ( "+a+" ).")}else r.log("Invalid module alias ( "+a+" ).")};this.getWrapper=function(d){d&&(b=d);return x(a,"define","require")};this.mergeInstances=function(b){b=b||{};for(var c in g)if(g.hasOwnProperty(c)){var d=g[c];b[d]||(b[d]=a.require(d))}return b};(function(){for(var a in h)if(h.hasOwnProperty(a)){var b=h[a];d[a]=b&&b.alias?{reserved:!0,standard:b.alias,args:b.args}:{reserved:!0}}}).call(a)});
a.exports=h},Vcb:function(a,e,h){a.config={singleton:!0};e=e("Class").extend(function(a){var e=this;a=(a=a.vcbParams)||{isVcbActive:!1,maxZindex:12E5,registerLoop:function(){},useZindex:function(){return!0},registerClickAction:function(){return null}};O(a,function(a,d){e[d]=a})});a.exports=e},Recommendations:function(a,e,h){a.config={singleton:!1};var k=e("Class").extend(function(a){var k=this,d=h("CGApi"),g=e("Deferred");this.setCategoryFilter=function(a,f,c){d.setCategoryFilter(a,f,c);return this};
this.setProductFilter=function(a,f,c){d.setProductFilter(a,f,c);return this};this.requestPage=function(a){var b=g();d.request({pageId:a},function(a){a?b.resolve():b.reject()});return b.promise()};this.getProducts=function(){return X(a)};this.getWrapper=function(){return x(k,"setCategoryFilter","setProductFilter","requestPage","getProducts")}});a.exports=k}};mmInitCallback(function(a,e,h){new function(a,e,h,d){function g(a,c,d){d=d.replace(/[^a-z0-9_]*/gi,"");c=F.mergeInstances(c);if(N(a)){var f=[];
var e=a.toString();e=e.substr(e.indexOf("(")+1,e.indexOf(")")-e.indexOf("(")-1).split(",");for(var g,h=0;h<e.length;h+=1)g=D(e[h]),c.hasOwnProperty(g)?f.push(c[g]):(r.warn("CD API: Module not found "+g+" Try to update CD API version."),f.push(void 0));try{a.apply({},f)}catch(R){R.message="Error in "+d+": "+R.message,r.error(R)}}else b(a,c,d)}function b(a,b,c){function f(a){a.apply({},g)}var e=[],g=[];N(d.scriptArgumentsWrapper)&&(b=d.scriptArgumentsWrapper(b));for(var h in b)b.hasOwnProperty(h)&&
(e.push(h),g.push(b[h]));a="function "+c+"(){function inner_"+c+"("+e.join(",")+"){"+a+"\n} try {\n applier(inner_"+c+");\n} catch (e) {\ne.message = 'Error in '+scriptName+': ' + e.message;\nconsole.error(e);\n};};\n"+c+"();//# sourceURL="+c+".js";try{ha.apply({},[a,c,f])}catch(R){R.message="Error in "+c+": "+R.message,r.error(R)}}function f(a){return"1.16"===a.HighLevelApiVersion}function c(a){a=w.require("Renderer",a);a.constructor=void 0;return a}function k(a){var b=l();b.modules=F.getWrapper(a);
b.campaign=a.campaign.getContext();b.renderer=c(a.campaign);return b}function q(a){if(a=C[a])return a=k({campaign:a}),a=F.mergeInstances(a)}function m(){var a=n();return a=F.mergeInstances(a)}function n(){var a=l();a.modules=F.getWrapper({});return a}function l(){return{site:J.getContext(),Deferred:w.requireClass("Deferred"),when:w.requireClass("When"),events:p.events.getWrapper(),actions:w.require("Action").getWrapper(),visitor:w.require("Visitor").getWrapper(),dom:w.require("Dom").getWrapper(),
widgets:w.require("Widgets").getWrapper(),dlp:w.require("Dlp").getWrapper(),cookies:w.require("Cookies").getWrapper(),recommendations:w.require("Recommendations",L).getWrapper()}}function y(b){K||(J=w.require("Site"),F=w.require("Modules"),K=!0);if(!d.skipPersistentData)for(var c=b.PersistData||[],e=c.length;e--;)a.setParam(c[e].Name,c[e].Value,a.baseStorage.storeStrategy.persistent,c[e].Expiration);var e,c=[],h=H(b.Campaigns||[],f),l=H(b.Scripts||[],f),p=w.requireClass("Campaign");for(e=0;e<l.length;e++)c.push({script:l[e]});
for(e=0;e<h.length;e++){l=h[e].Name;C[l]?C[l].updateData(h[e]):C[l]=new p(h[e]);L[l]=C[l].getRecommendations();for(var r=0;r<h[e].Scripts.length;r++)c.push({script:h[e].Scripts[r],campaign:C[l],campaignData:h[e]})}J.setPageExperiences(b.GenInfo||{});t=b.ServerAttributes;c.sort(function(a,b){return a.script.Order-b.script.Order});for(e=0;e<c.length;e++)b=c[e].script.Data,h=c[e].script.Name,(p=c[e].campaign)?(l=c[e].campaignData,g(b,k(c[e],{campaignData:l,campaign:p}),l.Name+"_"+h)):g(b,n(),"Site_"+
h);d.debug&&(d.debug["1.16"]={context:{getSiteScriptArguments:m,getCampaignScriptArguments:q}})}d=d||{};var p=this,u=[1,0];if(a.version.split(".")[0]!=u[0]||a.version.split(".")[1]<u[1])r.log("Loader have non compatible version with High level API.");else{var t={},u=function(){var a=location.search;if(window.parent!==window.self&&-1!==a.indexOf("original-url")&&(a=a.replace(/^\?/,"").split("&"),a=E(a,function(a){return 0===a.indexOf("original-url")}))){try{var b=decodeURIComponent(a).split("=").slice(1).join("=");
var c=/http(s)?:\/\/.*?([^/]|$)+/.exec(b)[0]}catch(ja){return}return c}}(),w=new ga({Engine:p},h,{isDlpEnabled:!I(u),dlpOrigin:u,vcbParams:d.vcbParams,cookieDomain:a.calcCookieDomain||a.cookie_domain||window.location.hostname.replace(/^www\./i,""),isBaseStorageSecure:a.baseStorage.isSecure,moduleExtensions:d.moduleExtensions});w.addModule("BaseStorage",function(b){b.config={singleton:!1};b.exports=function(b){return a.baseStorage(b.namespace)}});w.addModule("Engine",function(a){a.config={singleton:!0}});
var A=w.require("BaseStorage",{namespace:"mmengine"}),x={persistent:0,deferredRequest:1,request:2,page:3};this.storeStrategy=x;var z=[];z[x.page]={};z[x.request]={};var C={},J,F,K,L={};this.setParam=function(b,c,e,f){if(d.useLoaderStorage)a.setParam(b,c,e,f);else switch(e){case x.persistent:case x.deferredRequest:a.setParam(b,c,e);break;case x.request:case x.page:z[e][b]=c;break;default:r.log("Unknown store strategy: "+e)}};this.getParam=function(b,c){if(d.useLoaderStorage)return a.getParam(b,c);
switch(c){case x.persistent:case x.deferredRequest:return a.getParam(b,c);case x.request:case x.page:return z[c][b];default:r.log("Unknown store strategy: "+c)}};this.setData=function(a,b,c){A.set(a,b,c)};this.getData=function(a){return A.get(a)};this.clearData=function(a){A.set(a,null,-1)};this.getServerAttrs=function(){return t};this.CGRequest=function(b){if(!d.useLoaderStorage){var c=a.mergeParams(z[x.page],z[x.request]);z[x.request]={}}a.CGRequest(function(a){N(b)&&b(a)},c)};this.runElementScript=
function(a,b,d,e){b=a.getElement(b);var f=l();f.modules=F.getWrapper();f.campaign=a.getContext();f.renderer=c(a);f.element=b.clone();f.html=d.html;f.css=d.css;f.recommendations=w.require("Recommendations",L).getWrapper();g(e,f,a.getName()+"_"+b.Name+"_"+b.VariantName)};this.events=w.require("EventsSite");d.skipResponseProcessing||y(e);a.on("response",y)}}(a,e,ia,h)})})()})();
